version: "3.8"
services:
  bot:
    build:
      context: .
    command: amqp
    environment:
      - PROVIDER=telegram
      - BOT_TOKEN=$BOT_TOKEN
      - RABBITMQ_HOST=test-rabbitmq
      - RABBITMQ_USER=services
      - RABBITMQ_PASS=$RABBITMQ_PASS


  # http mode configuration
  # bot:
  #   build:
  #     context: .
  #   command: http
  #   ports:
  #     - 8080:8080
  #   environment:
  #     - BOT_TOKEN=$BOT_TOKEN

  test-rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=services
      - RABBITMQ_DEFAULT_PASS=$RABBITMQ_PASS
    ports:
      - 5672:5672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 20s
      retries: 3
